### ISSUE TITLE
Icon Update

### ISSUE THREAD

**Issue by mtshrmn** [FRC-Utilities/QDriverStation-Mobile#1]
I have no idea how to use the github site, so I'm sorry if this is not the right place to post it. 
I saw the new android release for the project, and I was happy to see my design being carried over to the icon of the application. But, because I didn't think of the possibility of it coming to android, I didn't design it to match the other android app icons.  I decided to try and re-design the icon, and in my opinion I think I did a nice job. 

Here is the OLD icon on my screen:
![old icon demonstration](https://cloud.githubusercontent.com/assets/18540571/17077797/cb885032-50e6-11e6-888e-b3ba5cdda3bf.png)

And here is the NEW icon on my screen:
![new icon demonstration](https://cloud.githubusercontent.com/assets/18540571/17077798/dfbf033e-50e6-11e6-8119-41438333ed91.png)

If you liked the new change - [here](https://www.dropbox.com/s/g8q00bbsp4x5pk9/QDriverStation%20Icon%20Android.png?dl=0) is where you can download the new icon (the download is png)

P.S.
I can't wait to check the app on our team's robot!

**Comment by alex-spataru** [comment]
Thanks for the new icon! It looks awesome!

**Comment by alex-spataru** [comment]
I updated the Android icons and the logo in the About dialog, thanks!
