### ISSUE TITLE
Add support for the 2017 protocol 

### ISSUE THREAD

**Issue by Deckee** [FRC-Utilities/QDriverStation-Mobile#10]
The protocol list lacks 2017 which most robots run.

**Comment by alex-spataru** [comment]
The 2017 protocol is exactly the same as the 2015/16 communication protocol. I added 2016 as a different protocol because it uses a different robot address than the 2015 comm. protocol (roboRIO-XXYY-FRC.local instead of roboRIO-XXYY.local).
