### ISSUE TITLE
QDriverStation website doesn't explicitly mention that app is on Play Store.

### ISSUE THREAD

**Issue by GaganBhat** [FRC-Utilities/QDriverStation-Mobile#11]
![image](https://user-images.githubusercontent.com/25236969/39959402-a1f42b50-55d6-11e8-95ec-68b28d11af4d.png)
"Here" should hyperlink to the play store link of the application. The website doesn't explicitly mention the app being on playstore so many people who I have directed to here end up getting lost. 

Just a small but functional fix =)

**Comment by alex-spataru** [comment]
Good idea, I'll update the website in a moment!
