### ISSUE TITLE
Can't use two thumbsticks at the same time

### ISSUE THREAD

**Issue by randomtestfive** [FRC-Utilities/QDriverStation-Mobile#2]
Only one thumbstick can be used at a time, which makes using a drive system like tank drive impossible.

**Comment by alex-spataru** [comment]
Thanks for the report! I am working on your issue right now, I will notify you when its fixed.

**Comment by alex-spataru** [comment]
I fixed your issue, you can get the latest version [here](https://github.com/FRC-Utilities/QDriverStation-Mobile/releases/latest). Thanks for the feedback!

**Comment by randomtestfive** [comment]
I can't get communications with the latest version. Tested with both 16.07.2, which worked, and 16.08, which didn't.

**Comment by alex-spataru** [comment]
In some cases, you will need to input your robot's static IP in the _Preferences_ page, for example, the IP of my team's robot is 10.37.94.21. Although I added mDNS support for the QDriverStation, sometimes the mDNS is able to obtain only the IPv6, which may have some problems with Qt sockets.
