### ISSUE TITLE
No icon in app drawer or homescreen

### ISSUE THREAD

**Issue by Wazzaps** [FRC-Utilities/QDriverStation-Mobile#3]
Im installing the app, I have two options, done and open. Open opens the app normally, and done takes me back to the home screen. When I press done or exit the app the app doesnt show on the drawer, or even in search. It only shows in settings>apps.

**Comment by Wazzaps** [comment]
It seems like after a restart it shows up.

**Comment by alex-spataru** [comment]
Yeah, it could have been the launcher that you are using or something...Could you tell me which launcher application (or Android phone) are you using? It could be useful to put a warning in the README to avoid confusing the users when this happens (I have received similar e-mails in the past, so its a common issue).

**Comment by Wazzaps** [comment]
LG G3 - Lollipop Cyanogen mod
Nova launcher

Yea probably indexing didnt happen for some reason. Anyway great application. Any planned smartdashboard support? (or atleast camera stream)

**Comment by alex-spataru** [comment]
Thanks for the info! I also use Cyanogen :+1: I will add the camera stream to the TODO list, I will begin working on it as soon as I finish other side-projects.

**Comment by Wazzaps** [comment]
If you need a reference I have implemented it in my own project [here](https://github.com/Wazzaps/PCRobot/blob/master/src/com/gmail/secondlifedvi/PCRobotController/RobotWebCamera.java). (Just delete the OpenCv stuff)

**Comment by alex-spataru** [comment]
Thanks for the reference, I will take a look at it!
