### ISSUE TITLE
[IDEA] network activity probe

### ISSUE THREAD

**Issue by Deckee** [FRC-Utilities/QDriverStation-Mobile#9]
make network in mb/s or kb/s and maybe a connection active incator,

**Comment by alex-spataru** [comment]
I'll take a look at implementing an indicator with the sent/received MB. The 'connection active' indicator is already implemented with the communications checkbox.

**Comment by alex-spataru** [comment]
I created a simple network usage indicator, the update will be live in the Play Store in a few moments. Thanks for the idea!
